### ISSUE TITLE
U otázky 4 zdůraznit, že pro vertikální vystředění mají sloupečky zůstat na jednom řádku

### ISSUE THREAD

**Issue by FilipChalupa** [Czechitas-podklady-WEB/daweb-test#21]
Možná přidat ilustrační obrázek?

**Comment by FilipJirsak** [comment]
Ilustrační obrázek by pomohl. Večer u piva se o tomhle zadání vedla vášnivá debata, co přesně znamená „zarovnat vertikálně“ :-)

**Comment by lrolecek** [comment]
My děláme test právě teď a před chvíli se sešla skupinka dotazů na to samé. Takže určitě přidat obrázek a možná i upravit text. Protože opravdu jsme mysleli vertikálně na střed prvku row (`align-content`) nebo v rámci řádku vertikálně na střed k sobě navzájem (`align-items`). Myslím, že jsme zamýšleli `align-items`, ale text fakticky popisuje spíš chování `align-content`.

**Comment by FilipJirsak** [comment]
Namaluju SVG.

**Comment by FilipJirsak** [comment]
Tohle už bylo vyřešeno PR https://github.com/Czechitas-podklady-WEB/daweb-test/pull/25 Máte pocit, že je k tomu potřeba ještě něco, nebo můžu issue uzavřít?
