### ISSUE TITLE
U otázky 9 pár lidí váhalo, zda mají pole jen vytvořit

### ISSUE THREAD

**Issue by lrolecek** [Czechitas-podklady-WEB/daweb-test#22]
U otázky 9 se spousta holek divila, zda mají pole jenom vytvořit nebo s ním i něco dělat. Zadání otázky podle mě není nijak zavádějící, ale možná na základě této zkušenosti zdůraznit, že fakt stačí pole jenom vytvořit, ať se zmatení vyhneme preventivně.

**Comment by FilipJirsak** [comment]
@FilipChalupa: Stačí jen na konec doplnit, že se má pole vypsat do konzole.
@podlomar: Aby do odpovědního formuláře nezkopírovaly jenom vypsané pole z konzole.

Začít:
> Jako odpověď napište JavaScriptový kód, který do proměnné `lednice` uloží pole objektů…
