### ISSUE TITLE
Otázka 14/15 několik holek nevědělo, zda mají obrázky avatarů kopírovat do svého projektu

### ISSUE THREAD

**Issue by lrolecek** [Czechitas-podklady-WEB/daweb-test#23]
Několik holek se snažilo obrázky avatarů kopírovat lokálně do svých projektů. Nevím proč. V zadání o tom není žádná zmínka, ale jim v příkladu 14 nějak nedošlo, že ten avatar nalinkovaný přímo z GitHubu pak bude takhle nalinkovaný u všech vtipů.

Stalo se to asi u 2 nebo 3 holek, takže žádný velký problém. Ale opět by možná bylo dobré to v textu zdůraznit, abychom preventivně předcházeli zmatení.

**Comment by FilipJirsak** [comment]
Otázky 14 a 15 se rozdělí, aby na sebe nenavazovaly. Nějaké nápady má @marketaanezka, zkonzultuje to s @podlomar.

**Comment by FilipChalupa** [comment]
Martin navrhuje předpřipravit kus kód a po účastnicích chtít nějaké drobečky doplnit.

**Comment by FilipJirsak** [comment]
V rámci #41 jsem obrázky tlačítek přidal rovnou do šablony repository, tj. nebude důvod kopírovat žádné soubory – měl by tedy být o důvod méně, proč kopírovat obrázky avatarů.
